<?php
// $Id: cckpassword.module,v 1.95.2.30 2009/07/18 01:18:07 markuspetrux Exp $

/**
 * @file
 * Defines simple cckpassword field types.
 */

/**
 * Implementation of hook_theme().
 */
function cckpassword_theme() {
  return array(
    'text_formatter_default' => array(
      'arguments' => array('element' => NULL),
    ),
  );
}

/**
 * Implementation of hook_field_info().
 */
function cckpassword_field_info() {
  return array(
    'cckpassword' => array(
      'label' => t('Password'),
      'description' => t('Store password in the database.'),
    ),
  );
}

/**
 * Implementation of hook_field_settings().
 */
function cckpassword_field_settings($op, $field) {
  switch ($op) {
    case 'form':
      return array();
    case 'database columns':
        $columns['value'] = array(
          'type' => 'varchar',
          'length' => 32,
          'not null' => FALSE, 
          'sortable' => TRUE,
          'views' => TRUE
        );
      return $columns;
  }
}

/**
 * Implementation of hook_field().
 */
function cckpassword_field($op, &$node, $field, &$items, $teaser, $page) {
  switch ($op) {
    case 'presave':
      $field_name = $field['field_name'];
      $old_vals = content_storage('load',$node);
      $old_vals = $old_vals[$field_name] ;
      if (is_array($items)) {
        
        foreach ($items as $delta => $item) {
          $error_element = isset($item['_error_element']) ? $item['_error_element'] : '';
          if (is_array($item) && isset($item['_error_element'])) unset($item['_error_element']);
          if (!empty($item['value'])) {
            $items[$delta]['value'] = md5($item['value']);
          } elseif ($item['delete']) {
            $items[$delta]['value'] =  '';
          } elseif ($old_vals[$delta]) {
            $items[$delta] = $old_vals[$delta];
          }
        }
      } else {
        $items = $old_vals; 
      }
      
      $node->$field_name = $items;
      return $items;
  }
}

/**
 * Implementation of hook_content_is_empty().
 */
function cckpassword_content_is_empty($item, $field) {
  if (empty($item['value'])) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implementation of hook_field_formatter_info().
 */
function cckpassword_field_formatter_info() {
  return array(
    'default' => array(
      'label' => t('None'),
      'field types' => array('cckpassword'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
  );
}

/**
 * Theme function for 'default' cckpassword field formatter.
 */
function theme_cckpassword_formatter_default($element) {
  return '';
}
/**
 * Implementation of hook_widget_info().
 *
 */
function cckpassword_widget_info() {
  return array(
    'cckpassword_cckpasswordfield' => array(
      'label' => t('Plain Password field'),
      'field types' => array('cckpassword'),
      'multiple values' => CONTENT_HANDLE_CORE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
    'cckpassword_cckpassworddrupal' => array(
      'label' => t('Drupal password field'),
      'field types' => array('cckpassword'),
      'multiple values' => CONTENT_HANDLE_CORE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
  );
}



/**
 * Implementation of hook_widget().
 *
 */
function cckpassword_widget(&$form, &$form_state, $field, $items, $delta = 0) {
  $widget = $field['widget']['type']=='cckpassword_cckpasswordfield';
  if(empty($widget)){
    _user_password_dynamic_validation();
     $element['value'] = array(
      '#type' => 'password_confirm',
    );
  } else {
     $element['value'] = array(
      '#type' => 'password',
      '#default_value' => '',
    );
  }
  if ($items[$delta]['value']) {
    $element['delete'] = array(
      '#type'=>'checkbox',
      '#title'=> t('Delete current password'),
      '#default_value'=> 0,
    );
  }
  return $element;
}